tag:
  - math_word_problems
task: aime24_grail
dataset_path: Maxwell-Jia/AIME_2024
output_type: generate_until
training_split: train
fewshot_split: train
test_split: train
doc_to_text: "{{Problem}}"
doc_to_target: "<start_working_out>\n{{Solution}}\n</end_working_out>\n<SOLUTION>{{Answer}}</SOLUTION>"
process_results: !function utils.process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "<|im_end|>"
    - "<|endoftext|>"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 4096
repeats: 1
num_fewshot: 0
metadata:
  version: 1.0
