tag:
  - math_word_problems
task: amc2023_thinking
dataset_path: sparkle-reasoning/amc2023
output_type: generate_until
test_split: test
fewshot_split: test
doc_to_text: "{{question}}"
doc_to_target: "<start_working_out>\n{{solution}}\n</end_working_out>\n<SOLUTION>{{answer}}</SOLUTION>"
process_results: !function utils.process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "<|im_end|>"
    - "<|endoftext|>"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 4096
repeats: 1
num_fewshot: 0
metadata:
  version: 1.0
