tag:
  - math_word_problems
task: gsm8k_thinking
dataset_path: gsm8k
dataset_name: main
output_type: generate_until
test_split: test
fewshot_split: train
doc_to_text: "{{question}}"
doc_to_target: !function utils.doc_to_target
process_results: !function utils.process_results
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "<|im_end|>"
    - "<|endoftext|>"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
repeats: 1
num_fewshot: 0
metadata:
  version: 1.0
