dataset_path: EleutherAI/hendrycks_math
process_docs: !function utils.process_docs
output_type: generate_until
training_split: train
test_split: test
doc_to_text: "{{problem}}"
doc_to_target: "<start_working_out>\n{{solution}}\n</end_working_out>\n<SOLUTION>{{answer}}</SOLUTION>"
process_results: !function utils.process_results
generation_kwargs:
  until:
    - "<|im_end|>"
    - "<|endoftext|>"
  do_sample: false
  temperature: 0
  max_gen_toks: 2048
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
