group: hendrycks_math_thinking
task:
  - hendrycks_math_thinking_algebra
  - hendrycks_math_thinking_counting_and_prob
  - hendrycks_math_thinking_geometry
  - hendrycks_math_thinking_intermediate_algebra
  - hendrycks_math_thinking_num_theory
  - hendrycks_math_thinking_prealgebra
  - hendrycks_math_thinking_precalc
aggregate_metric_list:
  - metric: exact_match
    aggregation: mean
    weight_by_size: true
metadata:
  version: 1.0
